### ISSUE TITLE
using <image/> placement/scale/align attributes

### ISSUE THREAD

**Issue by MaxximeS** [Amplexor/com.amplexor.imagemap-pdf#4]
Hi everyone,

thank you for this great plugin !

However, in my final PDF, the clickable areas are located and scaled differently as compared with the displayed <image.
![image](https://user-images.githubusercontent.com/115228024/194545684-a09e2405-b34c-4117-8ae5-a1210db18367.png)

When using an <imagemap, it seems that the clickable areas defined by the <area elements are disturbed by the placement, scale and/or align attributes of the  <image element. 

Is there any way for the <imagemap to adjust on the placement/scale/align attribute of the <image that is used ?
How did you overcome this issue on your side ?

Thanks, Maxime

PS: FYI when doing HTML outputs, the clickable areas of the <imagemap adjust perfectly with the <image attributes.

**Comment by Nico-Amplexor** [comment]
Hello @MaxximeS, unfortunatly scale/align attributes are not supported yet by this plugin.

**Comment by pierat** [comment]
@Nico-Amplexor 

Bonjour Nicolas, 

I've added two features to your plugin :

- **scaling support** with a limitation where centering does not works at the same time (it is not possible to center a set of svg images because each one ave it's own width) 
- a new imagemap.hotspot.legend which enables to **remove the legend** of all hotspots below the image.

I would be glad to share these two functionalities with DITA-OT community if you give me write access to a git dev branch of the plugin. 

Merci, Pierre

**Comment by Nico-Amplexor** [comment]
Hello @pierat ,
Thank you for your contribution to this plugin.
To push your modifications you can fork this repository and after that open a pull-request on the dev branch (upstream repository).

**Comment by Nico-Amplexor** [comment]
Hello @pierat ,
Thank you for your contribution to this plugin.
To push your modifications you can fork this repository and after that open a pull-request on the dev branch (upstream repository).

**Comment by pierat** [comment]
Hello @Nico-Amplexor everything is done and a pull request is generated :)

**Comment by Nico-Amplexor** [comment]
Hello @MaxximeS and @pierat,
For information this repository was migrated to https://github.com/acolad-digital/com.acolad.imagemap-pdf
